server.port=9091
spring.application.name=edge-service

# Route: any request to /example/** on the edge service is forwarded to example-service on port 8085
spring.cloud.gateway.routes[0].id=example_route
spring.cloud.gateway.routes[0].uri=http://localhost:8085
spring.cloud.gateway.routes[0].predicates[0]=Path=/example/**
