server:
  port: 8090

spring:
  application:
    name: oauth2-client-app
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 905379511239-8bq8q8qd28mhr1arh26fq75uocpk0h0n.apps.googleusercontent.com
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: sub