CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN
    :NEW.LastModified := SYSDATE;
END;
/

UPDATE Customers
SET Balance = Balance + 1000
WHERE CustomerID = 1;

SELECT CustomerID,
       Name,
       Balance,
       LastModified
FROM Customers;

CREATE TABLE AuditLog (
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    AccountID NUMBER,
    Amount NUMBER,
    TransactionType VARCHAR2(20),
    AuditDate DATE
);

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog(
        TransactionID,
        AccountID,
        Amount,
        TransactionType,
        AuditDate
    )
    VALUES(
        :NEW.TransactionID,
        :NEW.AccountID,
        :NEW.Amount,
        :NEW.TransactionType,
        SYSDATE
    );
END;
/

INSERT INTO Transactions
VALUES(
    101,
    1,
    SYSDATE,
    'Deposit',
    1000
);

SELECT * FROM AuditLog;

CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON Transactions
FOR EACH ROW
DECLARE
    v_balance NUMBER;
BEGIN

    SELECT Balance
    INTO v_balance
    FROM Accounts
    WHERE AccountID = :NEW.AccountID;

    IF :NEW.TransactionType = 'Withdrawal'
       AND :NEW.Amount > v_balance THEN
        RAISE_APPLICATION_ERROR(
            -20010,
            'Insufficient Balance'
        );
    END IF;

    IF :NEW.TransactionType = 'Deposit'
       AND :NEW.Amount <= 0 THEN
        RAISE_APPLICATION_ERROR(
            -20011,
            'Deposit Amount Must Be Positive'
        );
    END IF;

END;
/

INSERT INTO Transactions
VALUES(
    102,
    1,
    SYSDATE,
    'Deposit',
    500
);

INSERT INTO Transactions
VALUES(
    103,
    1,
    SYSDATE,
    'Deposit',
    -500
);

INSERT INTO Transactions
VALUES(
    104,
    1,
    SYSDATE,
    'Withdrawal',
    100000
);